### ISSUE TITLE
Npm run build fails to compile

### ISSUE THREAD

**Issue by joshuanianji** [jlengrand/elm-firebase#10] opened 2020-09-13 18:54 UTC
Following the instructions on your README makes create-elm-app fail to compile when I run `npm run build`. I'm using Elm 0.19.1.

## Environment:
- Mac OSX Catalina (10.15.6)
- `node -v`: v12.13.0
- `npm -v`: 6.14.8
- Create-elm-app: 4.2.26

## Output

```shell
Creating an optimized production build...
Failed to compile.

static/js/vendors~main.3cc16f1f.chunk.js from UglifyJs
undefined

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elm-firebase@1.0.0 build: `elm-app build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the elm-firebase@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/joshua/.npm/_logs/2020-09-13T18_40_17_182Z-debug.log
```
Create-elm-app had an issue similar to this a while back, [but it was fixed in a new release](https://github.com/halfzebra/create-elm-app/issues/341). 

Interestingly enough, the older elm firebase projects from 19.0 I've manually upgraded to 19.1 a while back still works. I'm not sure if this is an error in the dependencies or on my part. The `package.json` files in the projects are identical.

**Comment by jlengrand** [comment] 2020-09-15 19:39
Ok, I can reproduce.

```
➜  elm-firebase git:(master) npm run build

> elm-firebase@1.0.0 build /Users/jlengrand/IdeaProjects/plop/elm-firebase
> elm-app build


Creating an optimized production build...
Failed to compile.

static/js/vendors~main.4bb2fbc5.chunk.js from UglifyJs
undefined

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elm-firebase@1.0.0 build: `elm-app build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the elm-firebase@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jlengrand/.npm/_logs/2020-09-15T19_38_45_314Z-debug.log
```

I updated the elm.json file last week to point to 0.19.1. Let me see if I can find what the issue is

**Comment by joshuanianji** [comment] 2020-09-16 21:01
Hey Julien, I think I got a better idea of what the error is. It turns out that my `package.json` files were different after all.

I downgraded the firebase version back to 6.6.3 and that fixed it. Firebase 7 may require different imports in `index.js`, but I'm not too familiar with javascript imports and whatnot.

**Comment by jlengrand** [comment] 2020-09-26 20:44
Closed by https://github.com/jlengrand/elm-firebase/pull/11. Thanks again @joshuanianji really a rocking PR, and I appreciate you took the time to report back!

I added CI in the repo to keep track of that in the future.

**Closed** 2020-09-26 20:44 UTC
